# Generated by Django 4.2.3 on 2023-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todokapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-09-08'),
            preserve_default=False,
        ),
    ]
